# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: false
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 17.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: This module allows you to select a vendor at the sale order line
    level
repo_name: sale_purchase_vendor_no_stock
repo_slug: purchase-workflow
repo_website: https://github.com/OCA/purchase-workflow
use_pyproject_toml: true
use_ruff: false

